name = "bolt-ai"
main = "build/server/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "build/client"

[build]
command = "pnpm install && pnpm run build"
